window.EPICState = {
  create() {
    return {
      state: "landing",
      loading: false,
      error: "",
      credentials: {
        username: "",
        password: "",
      },
      token: null,
      originalToken: null,
      impersonating: null,
      user: {
        id: "",
        username: "",
        role: "",
      },
      registration: {
        token: "",
        checking: false,
        valid: false,
        submitting: false,
        contestName: "",
        email: "",
        error: "",
        form: {
          first_name: "",
          last_name: "",
          phone_number: "",
          password: "",
          password_confirm: "",
        },
      },
      organizerRequest: {
        submitting: false,
        error: "",
        success: "",
        form: {
          first_name: "",
          last_name: "",
          email: "",
          phone_number: "",
          password: "",
          password_confirm: "",
        },
      },
      monitor: {
        monitoredContest: null,
        // Kept for legacy x-show guards only. The actual Chart.js instance
        // lives in this.$el._monitorChart so Alpine does not proxy it.
        monitorChart: null,
        monitorSocket: null,
        monitorError: "",
      },
      participant: {
        tab: "contests",
        dashboardLoaded: false,
        loadingContests: false,
        loadingActivity: false,
        submitting: false,
        activeContests: [],
        registrations: [],
        registeredContestIds: new Set(),
        connectedContest: null,
        latestObservation: {
          sequence_id: null,
          timestamp: "",
        },
        submissionPayload: JSON.stringify(
          {
            forecast: {
              sensor_id: [],
            },
          },
          null,
          2
        ),
        activity: [],
        error: "",
        success: "",
      },
      organizer: {
        tab: "contests",
        dashboardLoaded: false,
        loadingContests: false,
        loadingTemplates: false,
        loadingLeaderboardId: null,
        creating: false,
        deletingContestId: null,
        pausingContestId: null,
        catalogProfile: null,
        loadingCatalog: false,
        contests: [],
        templates: [],
        selectedTemplate: null,
        newStep: 1,
        form: {
          name: "",
          description: "",
          visibility: "PUBLIC",
          start_date: "",
          end_date: "",
          sampling_rate_hz: 1,
          twin_id: "",
          sensor_selections: [],
          fault_entries: [],
          initial_conditions: null,
          task_type: "FORECASTING",
          metric_ids: ["mae"],
          score_against: "ground_truth",
          target_variables: [],
          observation_horizon_days: 2,
          prediction_horizon_seconds: 3600,
        },
        expandedContestId: null,
        extendingContestId: null,
        newEndDate: "",
        leaderboards: {},
        invitations: {},
        registrations: {},
        loadingParticipantsId: null,
        inviteEmails: "",
        sendingInvites: false,
        error: "",
        success: "",
      },
      deleteModal: {
        open: false,
        contestName: "",
        confirm: () => {},
        cancel: () => {},
      },
      admin: {
        tab: "overview",
        dashboardLoaded: false,
        loadingOverview: false,
        loadingUsers: false,
        loadingOrganizerRequests: false,
        contests: [],
        users: [],
        organizerRequests: [],
        totalUsers: 0,
        totalOrganizerRequests: 0,
        organizerRequestStatusFilter: "PENDING",
        contestSortKey: "name",
        contestSortDirection: "asc",
        deletingContestId: null,
        pausingContestId: null,
        userSearch: "",
        createUserForm: {
          username: "",
          email: "",
          password: "",
          role: "PARTICIPANT",
        },
        creatingUser: false,
        showCreateUser: false,
        expandedContestId: null,
        invitations: {},
        registrations: {},
        loadingParticipantsId: null,
        inviteEmails: "",
        sendingInvites: false,
        error: "",
        success: "",
      },
      sensorChart: null,
      streamSocket: null,
    };
  },
};
